import { ConversationStatus, ConversationType } from '@/types/chat.types'
import type { IConversation } from '@/types/chat.types'

export interface StaffInfo {
  id: string
  name: string
  avatarUrl?: string | null
}

export interface IConversationWithStaff extends IConversation {
  staffInfo?: StaffInfo | null
}

const STAFF: StaffInfo[] = [
  { id: 's1', name: 'Minh Khoa',   avatarUrl: null },
  { id: 's2', name: 'Thu Hương',   avatarUrl: null },
  { id: 's3', name: 'Đức Anh',     avatarUrl: null },
]

function ago(minutes: number): string {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString()
}

export const MOCK_BOARD: Record<ConversationStatus, IConversationWithStaff[]> = {
  [ConversationStatus.QUEUE]: [
    {
      id: 'mock-q1',
      type: ConversationType.ORGANIZATION,
      status: ConversationStatus.QUEUE,
      partner: { id: 'u1', displayName: 'Nguyễn Văn An', email: 'an.nguyen@student.edu.vn', avatarUrl: null },
      supportFormData: {
        postId: 'p1',
        category: 'Electronics',
        subCategoryId: 'sc1',
        itemName: 'iPhone 15 Pro – Titan Black',
        color: 'Black',
        additionalDetails: 'Lost near the library entrance on the 2nd floor',
        imageUrls: ['https://picsum.photos/seed/iphone/200/200'],
        lostLocation: 'Library – 2nd floor',
        eventTime: null,
      },
      lastMessage: { senderId: 'u1', content: 'I left it on the reading desk around 3 PM', timestamp: ago(8) },
      lastMessageAt: ago(8),
      lastMessageContent: 'I left it on the reading desk around 3 PM',
      unreadCount: 2,
      staffInfo: null,
      createdAt: ago(30),
      updatedAt: ago(8),
    },
    {
      id: 'mock-q2',
      type: ConversationType.ORGANIZATION,
      status: ConversationStatus.QUEUE,
      partner: { id: 'u2', displayName: 'Trần Thị Bích', email: 'bich.tran@student.edu.vn', avatarUrl: null },
      supportFormData: {
        postId: 'p2',
        category: 'Accessories',
        subCategoryId: 'sc2',
        itemName: 'Blue canvas backpack – FPT logo',
        color: 'Blue',
        additionalDetails: 'Has a small tear on the left strap',
        imageUrls: ['https://picsum.photos/seed/backpack/200/200'],
        lostLocation: 'Cafeteria – B block',
        eventTime: null,
      },
      lastMessage: { senderId: 'u2', content: 'It has my laptop and notebooks inside, please help!', timestamp: ago(20) },
      lastMessageAt: ago(20),
      lastMessageContent: 'It has my laptop and notebooks inside, please help!',
      unreadCount: 1,
      staffInfo: null,
      createdAt: ago(45),
      updatedAt: ago(20),
    },
    {
      id: 'mock-q3',
      type: ConversationType.ORGANIZATION,
      status: ConversationStatus.QUEUE,
      partner: { id: 'u3', displayName: 'Lê Hoàng Phúc', email: 'phuc.le@student.edu.vn', avatarUrl: null },
      supportFormData: {
        postId: 'p3',
        category: 'Documents',
        subCategoryId: 'sc3',
        itemName: 'Student ID Card – FPT University',
        color: 'White',
        additionalDetails: null,
        imageUrls: null,
        lostLocation: 'Main gate security desk',
        eventTime: null,
      },
      lastMessage: { senderId: 'u3', content: 'I need it urgently for my exam tomorrow', timestamp: ago(5) },
      lastMessageAt: ago(5),
      lastMessageContent: 'I need it urgently for my exam tomorrow',
      unreadCount: 0,
      staffInfo: null,
      createdAt: ago(60),
      updatedAt: ago(5),
    },
  ],

  [ConversationStatus.IN_PROGRESS]: [
    {
      id: 'mock-ip1',
      type: ConversationType.ORGANIZATION,
      status: ConversationStatus.IN_PROGRESS,
      assignedStaffId: STAFF[0].id,
      partner: { id: 'u4', displayName: 'Phạm Quỳnh Anh', email: 'anh.pham@student.edu.vn', avatarUrl: null },
      supportFormData: {
        postId: 'p4',
        category: 'Electronics',
        subCategoryId: 'sc1',
        itemName: 'AirPods Pro (2nd gen) – White case',
        color: 'White',
        additionalDetails: 'Case has a small scratch on the lid',
        imageUrls: ['https://picsum.photos/seed/airpods/200/200'],
        lostLocation: 'Gym – locker room',
        eventTime: null,
      },
      lastMessage: { senderId: STAFF[0].id, content: 'We found a matching item, can you describe the scratch?', timestamp: ago(3) },
      lastMessageAt: ago(3),
      lastMessageContent: 'We found a matching item, can you describe the scratch?',
      unreadCount: 1,
      staffInfo: STAFF[0],
      createdAt: ago(90),
      updatedAt: ago(3),
    },
    {
      id: 'mock-ip2',
      type: ConversationType.ORGANIZATION,
      status: ConversationStatus.IN_PROGRESS,
      assignedStaffId: STAFF[1].id,
      partner: { id: 'u5', displayName: 'Võ Minh Tuấn', email: 'tuan.vo@student.edu.vn', avatarUrl: null },
      supportFormData: {
        postId: 'p5',
        category: 'Electronics',
        subCategoryId: 'sc1',
        itemName: 'MacBook Air M2 – Space Gray',
        color: 'Space Gray',
        additionalDetails: 'Sticker of a cat on the back cover',
        imageUrls: ['https://picsum.photos/seed/macbook/200/200'],
        lostLocation: 'Room 305 – Building A',
        eventTime: null,
      },
      lastMessage: { senderId: 'u5', content: 'Yes, the sticker is a white cat with blue eyes', timestamp: ago(15) },
      lastMessageAt: ago(15),
      lastMessageContent: 'Yes, the sticker is a white cat with blue eyes',
      unreadCount: 0,
      staffInfo: STAFF[1],
      createdAt: ago(120),
      updatedAt: ago(15),
    },
    {
      id: 'mock-ip3',
      type: ConversationType.ORGANIZATION,
      status: ConversationStatus.IN_PROGRESS,
      assignedStaffId: STAFF[2].id,
      partner: { id: 'u6', displayName: 'Hoàng Thị Lan', email: 'lan.hoang@student.edu.vn', avatarUrl: null },
      supportFormData: {
        postId: 'p6',
        category: 'Accessories',
        subCategoryId: 'sc4',
        itemName: 'Silver wristwatch – Casio Edifice',
        color: 'Silver',
        additionalDetails: 'Engraved initials "HTL" on the back',
        imageUrls: ['https://picsum.photos/seed/watch/200/200'],
        lostLocation: 'Swimming pool – changing room',
        eventTime: null,
      },
      lastMessage: { senderId: STAFF[2].id, content: 'Please come to the lost & found office to verify ownership', timestamp: ago(40) },
      lastMessageAt: ago(40),
      lastMessageContent: 'Please come to the lost & found office to verify ownership',
      unreadCount: 0,
      staffInfo: STAFF[2],
      createdAt: ago(180),
      updatedAt: ago(40),
    },
  ],

  [ConversationStatus.CLOSED]: [
    {
      id: 'mock-r1',
      type: ConversationType.ORGANIZATION,
      status: ConversationStatus.CLOSED,
      assignedStaffId: STAFF[0].id,
      partner: { id: 'u7', displayName: 'Đặng Quốc Huy', email: 'huy.dang@student.edu.vn', avatarUrl: null },
      supportFormData: {
        postId: 'p7',
        category: 'Accessories',
        subCategoryId: 'sc5',
        itemName: 'Keychain with 3 keys – Toyota remote',
        color: 'Black',
        additionalDetails: 'Toyota car key with a red lanyard',
        imageUrls: ['https://picsum.photos/seed/keys/200/200'],
        lostLocation: 'Parking lot – Level B1',
        eventTime: null,
      },
      lastMessage: { senderId: 'u7', content: 'Thank you so much! Got it back safely.', timestamp: ago(180) },
      lastMessageAt: ago(180),
      lastMessageContent: 'Thank you so much! Got it back safely.',
      unreadCount: 0,
      staffInfo: STAFF[0],
      createdAt: ago(300),
      updatedAt: ago(180),
    },
    {
      id: 'mock-r2',
      type: ConversationType.ORGANIZATION,
      status: ConversationStatus.CLOSED,
      assignedStaffId: STAFF[1].id,
      partner: { id: 'u8', displayName: 'Nguyễn Thị Mai', email: 'mai.nguyen@student.edu.vn', avatarUrl: null },
      supportFormData: {
        postId: 'p8',
        category: 'Personal Items',
        subCategoryId: 'sc6',
        itemName: 'Prescription glasses – round frame',
        color: 'Tortoise',
        additionalDetails: 'Diopter -2.5, stored in a brown leather case',
        imageUrls: ['https://picsum.photos/seed/glasses/200/200'],
        lostLocation: 'Lecture hall 201',
        eventTime: null,
      },
      lastMessage: { senderId: STAFF[1].id, content: 'Item successfully returned. Case closed.', timestamp: ago(240) },
      lastMessageAt: ago(240),
      lastMessageContent: 'Item successfully returned. Case closed.',
      unreadCount: 0,
      staffInfo: STAFF[1],
      createdAt: ago(360),
      updatedAt: ago(240),
    },
    {
      id: 'mock-r3',
      type: ConversationType.ORGANIZATION,
      status: ConversationStatus.CLOSED,
      assignedStaffId: STAFF[2].id,
      partner: { id: 'u9', displayName: 'Bùi Thanh Tùng', email: 'tung.bui@student.edu.vn', avatarUrl: null },
      supportFormData: {
        postId: 'p9',
        category: 'Clothing',
        subCategoryId: 'sc7',
        itemName: 'Black umbrella – Samsonite compact',
        color: 'Black',
        additionalDetails: null,
        imageUrls: ['https://picsum.photos/seed/umbrella/200/200'],
        lostLocation: 'Bus stop – Gate 2',
        eventTime: null,
      },
      lastMessage: { senderId: 'u9', content: 'Picked up, thanks a lot!', timestamp: ago(420) },
      lastMessageAt: ago(420),
      lastMessageContent: 'Picked up, thanks a lot!',
      unreadCount: 0,
      staffInfo: STAFF[2],
      createdAt: ago(600),
      updatedAt: ago(420),
    },
  ],
}
