/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleWelcomeRouteImport } from './routes/console/welcome'
import { Route as ConsoleProcessingRouteImport } from './routes/console/processing'
import { Route as ConsoleCreateOrganizationRouteImport } from './routes/console/create-organization'
import { Route as AuthSigninOrSignupRouteImport } from './routes/auth/signin-or-signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthRedirectRouteImport } from './routes/auth/redirect'
import { Route as AuthCreatePasswordRouteImport } from './routes/auth/create-password'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as MarketingUseCasesRouteImport } from './routes/_marketing/use-cases'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing/features'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingApplyRouteImport } from './routes/_marketing/apply'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as ConsoleStaffNotificationRouteImport } from './routes/console/staff/notification'
import { Route as ConsoleStaffInventorySearchRouteImport } from './routes/console/staff/inventory-search'
import { Route as ConsoleStaffInventoryAddItemRouteImport } from './routes/console/staff/inventory-add-item'
import { Route as ConsoleStaffInventoryRouteImport } from './routes/console/staff/inventory'
import { Route as ConsoleStaffFeedRouteImport } from './routes/console/staff/feed'
import { Route as ConsoleStaffChatRouteImport } from './routes/console/staff/chat'
import { Route as ConsoleAdminSettingRouteImport } from './routes/console/admin/setting'
import { Route as ConsoleAdminPlanRouteImport } from './routes/console/admin/plan'
import { Route as ConsoleAdminInviteEmployeeRouteImport } from './routes/console/admin/invite-employee'
import { Route as ConsoleAdminEmployeeRouteImport } from './routes/console/admin/employee'
import { Route as ConsoleAdminEditAccountRouteImport } from './routes/console/admin/edit-account'
import { Route as ConsoleAdminDashboardRouteImport } from './routes/console/admin/dashboard'
import { Route as ConsoleAdminBranchRouteImport } from './routes/console/admin/branch'
import { Route as ConsoleAdminEditEmployeeEmployeeIdRouteImport } from './routes/console/admin/edit-employee/$employeeId'
import { Route as ConsoleAdminEditBranchBranchIdRouteImport } from './routes/console/admin/edit-branch/$branchId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleWelcomeRoute = ConsoleWelcomeRouteImport.update({
  id: '/console/welcome',
  path: '/console/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleProcessingRoute = ConsoleProcessingRouteImport.update({
  id: '/console/processing',
  path: '/console/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleCreateOrganizationRoute =
  ConsoleCreateOrganizationRouteImport.update({
    id: '/console/create-organization',
    path: '/console/create-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSigninOrSignupRoute = AuthSigninOrSignupRouteImport.update({
  id: '/auth/signin-or-signup',
  path: '/auth/signin-or-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/auth/redirect',
  path: '/auth/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreatePasswordRoute = AuthCreatePasswordRouteImport.update({
  id: '/auth/create-password',
  path: '/auth/create-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/auth/check-email',
  path: '/auth/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingUseCasesRoute = MarketingUseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingApplyRoute = MarketingApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const ConsoleStaffNotificationRoute =
  ConsoleStaffNotificationRouteImport.update({
    id: '/console/staff/notification',
    path: '/console/staff/notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsoleStaffInventorySearchRoute =
  ConsoleStaffInventorySearchRouteImport.update({
    id: '/console/staff/inventory-search',
    path: '/console/staff/inventory-search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsoleStaffInventoryAddItemRoute =
  ConsoleStaffInventoryAddItemRouteImport.update({
    id: '/console/staff/inventory-add-item',
    path: '/console/staff/inventory-add-item',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsoleStaffInventoryRoute = ConsoleStaffInventoryRouteImport.update({
  id: '/console/staff/inventory',
  path: '/console/staff/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleStaffFeedRoute = ConsoleStaffFeedRouteImport.update({
  id: '/console/staff/feed',
  path: '/console/staff/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleStaffChatRoute = ConsoleStaffChatRouteImport.update({
  id: '/console/staff/chat',
  path: '/console/staff/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAdminSettingRoute = ConsoleAdminSettingRouteImport.update({
  id: '/console/admin/setting',
  path: '/console/admin/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAdminPlanRoute = ConsoleAdminPlanRouteImport.update({
  id: '/console/admin/plan',
  path: '/console/admin/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAdminInviteEmployeeRoute =
  ConsoleAdminInviteEmployeeRouteImport.update({
    id: '/console/admin/invite-employee',
    path: '/console/admin/invite-employee',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsoleAdminEmployeeRoute = ConsoleAdminEmployeeRouteImport.update({
  id: '/console/admin/employee',
  path: '/console/admin/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAdminEditAccountRoute = ConsoleAdminEditAccountRouteImport.update({
  id: '/console/admin/edit-account',
  path: '/console/admin/edit-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAdminDashboardRoute = ConsoleAdminDashboardRouteImport.update({
  id: '/console/admin/dashboard',
  path: '/console/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAdminBranchRoute = ConsoleAdminBranchRouteImport.update({
  id: '/console/admin/branch',
  path: '/console/admin/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAdminEditEmployeeEmployeeIdRoute =
  ConsoleAdminEditEmployeeEmployeeIdRouteImport.update({
    id: '/console/admin/edit-employee/$employeeId',
    path: '/console/admin/edit-employee/$employeeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsoleAdminEditBranchBranchIdRoute =
  ConsoleAdminEditBranchBranchIdRouteImport.update({
    id: '/console/admin/edit-branch/$branchId',
    path: '/console/admin/edit-branch/$branchId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/about': typeof MarketingAboutRoute
  '/apply': typeof MarketingApplyRoute
  '/contact': typeof MarketingContactRoute
  '/features': typeof MarketingFeaturesRoute
  '/pricing': typeof MarketingPricingRoute
  '/use-cases': typeof MarketingUseCasesRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signin-or-signup': typeof AuthSigninOrSignupRoute
  '/console/create-organization': typeof ConsoleCreateOrganizationRoute
  '/console/processing': typeof ConsoleProcessingRoute
  '/console/welcome': typeof ConsoleWelcomeRoute
  '/console/admin/branch': typeof ConsoleAdminBranchRoute
  '/console/admin/dashboard': typeof ConsoleAdminDashboardRoute
  '/console/admin/edit-account': typeof ConsoleAdminEditAccountRoute
  '/console/admin/employee': typeof ConsoleAdminEmployeeRoute
  '/console/admin/invite-employee': typeof ConsoleAdminInviteEmployeeRoute
  '/console/admin/plan': typeof ConsoleAdminPlanRoute
  '/console/admin/setting': typeof ConsoleAdminSettingRoute
  '/console/staff/chat': typeof ConsoleStaffChatRoute
  '/console/staff/feed': typeof ConsoleStaffFeedRoute
  '/console/staff/inventory': typeof ConsoleStaffInventoryRoute
  '/console/staff/inventory-add-item': typeof ConsoleStaffInventoryAddItemRoute
  '/console/staff/inventory-search': typeof ConsoleStaffInventorySearchRoute
  '/console/staff/notification': typeof ConsoleStaffNotificationRoute
  '/console/admin/edit-branch/$branchId': typeof ConsoleAdminEditBranchBranchIdRoute
  '/console/admin/edit-employee/$employeeId': typeof ConsoleAdminEditEmployeeEmployeeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/about': typeof MarketingAboutRoute
  '/apply': typeof MarketingApplyRoute
  '/contact': typeof MarketingContactRoute
  '/features': typeof MarketingFeaturesRoute
  '/pricing': typeof MarketingPricingRoute
  '/use-cases': typeof MarketingUseCasesRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signin-or-signup': typeof AuthSigninOrSignupRoute
  '/console/create-organization': typeof ConsoleCreateOrganizationRoute
  '/console/processing': typeof ConsoleProcessingRoute
  '/console/welcome': typeof ConsoleWelcomeRoute
  '/console/admin/branch': typeof ConsoleAdminBranchRoute
  '/console/admin/dashboard': typeof ConsoleAdminDashboardRoute
  '/console/admin/edit-account': typeof ConsoleAdminEditAccountRoute
  '/console/admin/employee': typeof ConsoleAdminEmployeeRoute
  '/console/admin/invite-employee': typeof ConsoleAdminInviteEmployeeRoute
  '/console/admin/plan': typeof ConsoleAdminPlanRoute
  '/console/admin/setting': typeof ConsoleAdminSettingRoute
  '/console/staff/chat': typeof ConsoleStaffChatRoute
  '/console/staff/feed': typeof ConsoleStaffFeedRoute
  '/console/staff/inventory': typeof ConsoleStaffInventoryRoute
  '/console/staff/inventory-add-item': typeof ConsoleStaffInventoryAddItemRoute
  '/console/staff/inventory-search': typeof ConsoleStaffInventorySearchRoute
  '/console/staff/notification': typeof ConsoleStaffNotificationRoute
  '/console/admin/edit-branch/$branchId': typeof ConsoleAdminEditBranchBranchIdRoute
  '/console/admin/edit-employee/$employeeId': typeof ConsoleAdminEditEmployeeEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_marketing': typeof MarketingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/apply': typeof MarketingApplyRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/use-cases': typeof MarketingUseCasesRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signin-or-signup': typeof AuthSigninOrSignupRoute
  '/console/create-organization': typeof ConsoleCreateOrganizationRoute
  '/console/processing': typeof ConsoleProcessingRoute
  '/console/welcome': typeof ConsoleWelcomeRoute
  '/console/admin/branch': typeof ConsoleAdminBranchRoute
  '/console/admin/dashboard': typeof ConsoleAdminDashboardRoute
  '/console/admin/edit-account': typeof ConsoleAdminEditAccountRoute
  '/console/admin/employee': typeof ConsoleAdminEmployeeRoute
  '/console/admin/invite-employee': typeof ConsoleAdminInviteEmployeeRoute
  '/console/admin/plan': typeof ConsoleAdminPlanRoute
  '/console/admin/setting': typeof ConsoleAdminSettingRoute
  '/console/staff/chat': typeof ConsoleStaffChatRoute
  '/console/staff/feed': typeof ConsoleStaffFeedRoute
  '/console/staff/inventory': typeof ConsoleStaffInventoryRoute
  '/console/staff/inventory-add-item': typeof ConsoleStaffInventoryAddItemRoute
  '/console/staff/inventory-search': typeof ConsoleStaffInventorySearchRoute
  '/console/staff/notification': typeof ConsoleStaffNotificationRoute
  '/console/admin/edit-branch/$branchId': typeof ConsoleAdminEditBranchBranchIdRoute
  '/console/admin/edit-employee/$employeeId': typeof ConsoleAdminEditEmployeeEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/apply'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/use-cases'
    | '/auth/check-email'
    | '/auth/create-password'
    | '/auth/redirect'
    | '/auth/signin'
    | '/auth/signin-or-signup'
    | '/console/create-organization'
    | '/console/processing'
    | '/console/welcome'
    | '/console/admin/branch'
    | '/console/admin/dashboard'
    | '/console/admin/edit-account'
    | '/console/admin/employee'
    | '/console/admin/invite-employee'
    | '/console/admin/plan'
    | '/console/admin/setting'
    | '/console/staff/chat'
    | '/console/staff/feed'
    | '/console/staff/inventory'
    | '/console/staff/inventory-add-item'
    | '/console/staff/inventory-search'
    | '/console/staff/notification'
    | '/console/admin/edit-branch/$branchId'
    | '/console/admin/edit-employee/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/about'
    | '/apply'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/use-cases'
    | '/auth/check-email'
    | '/auth/create-password'
    | '/auth/redirect'
    | '/auth/signin'
    | '/auth/signin-or-signup'
    | '/console/create-organization'
    | '/console/processing'
    | '/console/welcome'
    | '/console/admin/branch'
    | '/console/admin/dashboard'
    | '/console/admin/edit-account'
    | '/console/admin/employee'
    | '/console/admin/invite-employee'
    | '/console/admin/plan'
    | '/console/admin/setting'
    | '/console/staff/chat'
    | '/console/staff/feed'
    | '/console/staff/inventory'
    | '/console/staff/inventory-add-item'
    | '/console/staff/inventory-search'
    | '/console/staff/notification'
    | '/console/admin/edit-branch/$branchId'
    | '/console/admin/edit-employee/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/_marketing'
    | '/dashboard'
    | '/_marketing/about'
    | '/_marketing/apply'
    | '/_marketing/contact'
    | '/_marketing/features'
    | '/_marketing/pricing'
    | '/_marketing/use-cases'
    | '/auth/check-email'
    | '/auth/create-password'
    | '/auth/redirect'
    | '/auth/signin'
    | '/auth/signin-or-signup'
    | '/console/create-organization'
    | '/console/processing'
    | '/console/welcome'
    | '/console/admin/branch'
    | '/console/admin/dashboard'
    | '/console/admin/edit-account'
    | '/console/admin/employee'
    | '/console/admin/invite-employee'
    | '/console/admin/plan'
    | '/console/admin/setting'
    | '/console/staff/chat'
    | '/console/staff/feed'
    | '/console/staff/inventory'
    | '/console/staff/inventory-add-item'
    | '/console/staff/inventory-search'
    | '/console/staff/notification'
    | '/console/admin/edit-branch/$branchId'
    | '/console/admin/edit-employee/$employeeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketingRoute: typeof MarketingRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthCreatePasswordRoute: typeof AuthCreatePasswordRoute
  AuthRedirectRoute: typeof AuthRedirectRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSigninOrSignupRoute: typeof AuthSigninOrSignupRoute
  ConsoleCreateOrganizationRoute: typeof ConsoleCreateOrganizationRoute
  ConsoleProcessingRoute: typeof ConsoleProcessingRoute
  ConsoleWelcomeRoute: typeof ConsoleWelcomeRoute
  ConsoleAdminBranchRoute: typeof ConsoleAdminBranchRoute
  ConsoleAdminDashboardRoute: typeof ConsoleAdminDashboardRoute
  ConsoleAdminEditAccountRoute: typeof ConsoleAdminEditAccountRoute
  ConsoleAdminEmployeeRoute: typeof ConsoleAdminEmployeeRoute
  ConsoleAdminInviteEmployeeRoute: typeof ConsoleAdminInviteEmployeeRoute
  ConsoleAdminPlanRoute: typeof ConsoleAdminPlanRoute
  ConsoleAdminSettingRoute: typeof ConsoleAdminSettingRoute
  ConsoleStaffChatRoute: typeof ConsoleStaffChatRoute
  ConsoleStaffFeedRoute: typeof ConsoleStaffFeedRoute
  ConsoleStaffInventoryRoute: typeof ConsoleStaffInventoryRoute
  ConsoleStaffInventoryAddItemRoute: typeof ConsoleStaffInventoryAddItemRoute
  ConsoleStaffInventorySearchRoute: typeof ConsoleStaffInventorySearchRoute
  ConsoleStaffNotificationRoute: typeof ConsoleStaffNotificationRoute
  ConsoleAdminEditBranchBranchIdRoute: typeof ConsoleAdminEditBranchBranchIdRoute
  ConsoleAdminEditEmployeeEmployeeIdRoute: typeof ConsoleAdminEditEmployeeEmployeeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/welcome': {
      id: '/console/welcome'
      path: '/console/welcome'
      fullPath: '/console/welcome'
      preLoaderRoute: typeof ConsoleWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/processing': {
      id: '/console/processing'
      path: '/console/processing'
      fullPath: '/console/processing'
      preLoaderRoute: typeof ConsoleProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/create-organization': {
      id: '/console/create-organization'
      path: '/console/create-organization'
      fullPath: '/console/create-organization'
      preLoaderRoute: typeof ConsoleCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin-or-signup': {
      id: '/auth/signin-or-signup'
      path: '/auth/signin-or-signup'
      fullPath: '/auth/signin-or-signup'
      preLoaderRoute: typeof AuthSigninOrSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/redirect': {
      id: '/auth/redirect'
      path: '/auth/redirect'
      fullPath: '/auth/redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-password': {
      id: '/auth/create-password'
      path: '/auth/create-password'
      fullPath: '/auth/create-password'
      preLoaderRoute: typeof AuthCreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/auth/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/use-cases': {
      id: '/_marketing/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof MarketingUseCasesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/apply': {
      id: '/_marketing/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof MarketingApplyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/console/staff/notification': {
      id: '/console/staff/notification'
      path: '/console/staff/notification'
      fullPath: '/console/staff/notification'
      preLoaderRoute: typeof ConsoleStaffNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/staff/inventory-search': {
      id: '/console/staff/inventory-search'
      path: '/console/staff/inventory-search'
      fullPath: '/console/staff/inventory-search'
      preLoaderRoute: typeof ConsoleStaffInventorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/staff/inventory-add-item': {
      id: '/console/staff/inventory-add-item'
      path: '/console/staff/inventory-add-item'
      fullPath: '/console/staff/inventory-add-item'
      preLoaderRoute: typeof ConsoleStaffInventoryAddItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/staff/inventory': {
      id: '/console/staff/inventory'
      path: '/console/staff/inventory'
      fullPath: '/console/staff/inventory'
      preLoaderRoute: typeof ConsoleStaffInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/staff/feed': {
      id: '/console/staff/feed'
      path: '/console/staff/feed'
      fullPath: '/console/staff/feed'
      preLoaderRoute: typeof ConsoleStaffFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/staff/chat': {
      id: '/console/staff/chat'
      path: '/console/staff/chat'
      fullPath: '/console/staff/chat'
      preLoaderRoute: typeof ConsoleStaffChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin/setting': {
      id: '/console/admin/setting'
      path: '/console/admin/setting'
      fullPath: '/console/admin/setting'
      preLoaderRoute: typeof ConsoleAdminSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin/plan': {
      id: '/console/admin/plan'
      path: '/console/admin/plan'
      fullPath: '/console/admin/plan'
      preLoaderRoute: typeof ConsoleAdminPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin/invite-employee': {
      id: '/console/admin/invite-employee'
      path: '/console/admin/invite-employee'
      fullPath: '/console/admin/invite-employee'
      preLoaderRoute: typeof ConsoleAdminInviteEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin/employee': {
      id: '/console/admin/employee'
      path: '/console/admin/employee'
      fullPath: '/console/admin/employee'
      preLoaderRoute: typeof ConsoleAdminEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin/edit-account': {
      id: '/console/admin/edit-account'
      path: '/console/admin/edit-account'
      fullPath: '/console/admin/edit-account'
      preLoaderRoute: typeof ConsoleAdminEditAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin/dashboard': {
      id: '/console/admin/dashboard'
      path: '/console/admin/dashboard'
      fullPath: '/console/admin/dashboard'
      preLoaderRoute: typeof ConsoleAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin/branch': {
      id: '/console/admin/branch'
      path: '/console/admin/branch'
      fullPath: '/console/admin/branch'
      preLoaderRoute: typeof ConsoleAdminBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin/edit-employee/$employeeId': {
      id: '/console/admin/edit-employee/$employeeId'
      path: '/console/admin/edit-employee/$employeeId'
      fullPath: '/console/admin/edit-employee/$employeeId'
      preLoaderRoute: typeof ConsoleAdminEditEmployeeEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin/edit-branch/$branchId': {
      id: '/console/admin/edit-branch/$branchId'
      path: '/console/admin/edit-branch/$branchId'
      fullPath: '/console/admin/edit-branch/$branchId'
      preLoaderRoute: typeof ConsoleAdminEditBranchBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingApplyRoute: typeof MarketingApplyRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingUseCasesRoute: typeof MarketingUseCasesRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingApplyRoute: MarketingApplyRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingUseCasesRoute: MarketingUseCasesRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketingRoute: MarketingRouteWithChildren,
  DashboardRoute: DashboardRoute,
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthCreatePasswordRoute: AuthCreatePasswordRoute,
  AuthRedirectRoute: AuthRedirectRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSigninOrSignupRoute: AuthSigninOrSignupRoute,
  ConsoleCreateOrganizationRoute: ConsoleCreateOrganizationRoute,
  ConsoleProcessingRoute: ConsoleProcessingRoute,
  ConsoleWelcomeRoute: ConsoleWelcomeRoute,
  ConsoleAdminBranchRoute: ConsoleAdminBranchRoute,
  ConsoleAdminDashboardRoute: ConsoleAdminDashboardRoute,
  ConsoleAdminEditAccountRoute: ConsoleAdminEditAccountRoute,
  ConsoleAdminEmployeeRoute: ConsoleAdminEmployeeRoute,
  ConsoleAdminInviteEmployeeRoute: ConsoleAdminInviteEmployeeRoute,
  ConsoleAdminPlanRoute: ConsoleAdminPlanRoute,
  ConsoleAdminSettingRoute: ConsoleAdminSettingRoute,
  ConsoleStaffChatRoute: ConsoleStaffChatRoute,
  ConsoleStaffFeedRoute: ConsoleStaffFeedRoute,
  ConsoleStaffInventoryRoute: ConsoleStaffInventoryRoute,
  ConsoleStaffInventoryAddItemRoute: ConsoleStaffInventoryAddItemRoute,
  ConsoleStaffInventorySearchRoute: ConsoleStaffInventorySearchRoute,
  ConsoleStaffNotificationRoute: ConsoleStaffNotificationRoute,
  ConsoleAdminEditBranchBranchIdRoute: ConsoleAdminEditBranchBranchIdRoute,
  ConsoleAdminEditEmployeeEmployeeIdRoute:
    ConsoleAdminEditEmployeeEmployeeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
