/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSigninOrSignupRouteImport } from './routes/auth/signin-or-signup'
import { Route as MarketingUseCasesRouteImport } from './routes/_marketing/use-cases'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing/features'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingApplyRouteImport } from './routes/_marketing/apply'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninOrSignupRoute = AuthSigninOrSignupRouteImport.update({
  id: '/auth/signin-or-signup',
  path: '/auth/signin-or-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingUseCasesRoute = MarketingUseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingApplyRoute = MarketingApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/about': typeof MarketingAboutRoute
  '/apply': typeof MarketingApplyRoute
  '/contact': typeof MarketingContactRoute
  '/features': typeof MarketingFeaturesRoute
  '/pricing': typeof MarketingPricingRoute
  '/use-cases': typeof MarketingUseCasesRoute
  '/auth/signin-or-signup': typeof AuthSigninOrSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/about': typeof MarketingAboutRoute
  '/apply': typeof MarketingApplyRoute
  '/contact': typeof MarketingContactRoute
  '/features': typeof MarketingFeaturesRoute
  '/pricing': typeof MarketingPricingRoute
  '/use-cases': typeof MarketingUseCasesRoute
  '/auth/signin-or-signup': typeof AuthSigninOrSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_marketing': typeof MarketingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/apply': typeof MarketingApplyRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/use-cases': typeof MarketingUseCasesRoute
  '/auth/signin-or-signup': typeof AuthSigninOrSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/apply'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/use-cases'
    | '/auth/signin-or-signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/about'
    | '/apply'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/use-cases'
    | '/auth/signin-or-signup'
  id:
    | '__root__'
    | '/'
    | '/_marketing'
    | '/dashboard'
    | '/_marketing/about'
    | '/_marketing/apply'
    | '/_marketing/contact'
    | '/_marketing/features'
    | '/_marketing/pricing'
    | '/_marketing/use-cases'
    | '/auth/signin-or-signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketingRoute: typeof MarketingRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  AuthSigninOrSignupRoute: typeof AuthSigninOrSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin-or-signup': {
      id: '/auth/signin-or-signup'
      path: '/auth/signin-or-signup'
      fullPath: '/auth/signin-or-signup'
      preLoaderRoute: typeof AuthSigninOrSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/use-cases': {
      id: '/_marketing/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof MarketingUseCasesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/apply': {
      id: '/_marketing/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof MarketingApplyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingApplyRoute: typeof MarketingApplyRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingUseCasesRoute: typeof MarketingUseCasesRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingApplyRoute: MarketingApplyRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingUseCasesRoute: MarketingUseCasesRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketingRoute: MarketingRouteWithChildren,
  DashboardRoute: DashboardRoute,
  AuthSigninOrSignupRoute: AuthSigninOrSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
