/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleWelcomeRouteImport } from './routes/console/welcome'
import { Route as ConsoleProcessingRouteImport } from './routes/console/processing'
import { Route as ConsoleCreateOrganizationRouteImport } from './routes/console/create-organization'
import { Route as AuthSigninOrSignupRouteImport } from './routes/auth/signin-or-signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthRedirectRouteImport } from './routes/auth/redirect'
import { Route as AuthCreatePasswordRouteImport } from './routes/auth/create-password'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as MarketingUseCasesRouteImport } from './routes/_marketing/use-cases'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing/features'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingApplyRouteImport } from './routes/_marketing/apply'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleWelcomeRoute = ConsoleWelcomeRouteImport.update({
  id: '/console/welcome',
  path: '/console/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleProcessingRoute = ConsoleProcessingRouteImport.update({
  id: '/console/processing',
  path: '/console/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleCreateOrganizationRoute =
  ConsoleCreateOrganizationRouteImport.update({
    id: '/console/create-organization',
    path: '/console/create-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSigninOrSignupRoute = AuthSigninOrSignupRouteImport.update({
  id: '/auth/signin-or-signup',
  path: '/auth/signin-or-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/auth/redirect',
  path: '/auth/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreatePasswordRoute = AuthCreatePasswordRouteImport.update({
  id: '/auth/create-password',
  path: '/auth/create-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/auth/check-email',
  path: '/auth/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingUseCasesRoute = MarketingUseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingApplyRoute = MarketingApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/about': typeof MarketingAboutRoute
  '/apply': typeof MarketingApplyRoute
  '/contact': typeof MarketingContactRoute
  '/features': typeof MarketingFeaturesRoute
  '/pricing': typeof MarketingPricingRoute
  '/use-cases': typeof MarketingUseCasesRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signin-or-signup': typeof AuthSigninOrSignupRoute
  '/console/create-organization': typeof ConsoleCreateOrganizationRoute
  '/console/processing': typeof ConsoleProcessingRoute
  '/console/welcome': typeof ConsoleWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/about': typeof MarketingAboutRoute
  '/apply': typeof MarketingApplyRoute
  '/contact': typeof MarketingContactRoute
  '/features': typeof MarketingFeaturesRoute
  '/pricing': typeof MarketingPricingRoute
  '/use-cases': typeof MarketingUseCasesRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signin-or-signup': typeof AuthSigninOrSignupRoute
  '/console/create-organization': typeof ConsoleCreateOrganizationRoute
  '/console/processing': typeof ConsoleProcessingRoute
  '/console/welcome': typeof ConsoleWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_marketing': typeof MarketingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/apply': typeof MarketingApplyRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/use-cases': typeof MarketingUseCasesRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signin-or-signup': typeof AuthSigninOrSignupRoute
  '/console/create-organization': typeof ConsoleCreateOrganizationRoute
  '/console/processing': typeof ConsoleProcessingRoute
  '/console/welcome': typeof ConsoleWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/apply'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/use-cases'
    | '/auth/check-email'
    | '/auth/create-password'
    | '/auth/redirect'
    | '/auth/signin'
    | '/auth/signin-or-signup'
    | '/console/create-organization'
    | '/console/processing'
    | '/console/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/about'
    | '/apply'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/use-cases'
    | '/auth/check-email'
    | '/auth/create-password'
    | '/auth/redirect'
    | '/auth/signin'
    | '/auth/signin-or-signup'
    | '/console/create-organization'
    | '/console/processing'
    | '/console/welcome'
  id:
    | '__root__'
    | '/'
    | '/_marketing'
    | '/dashboard'
    | '/_marketing/about'
    | '/_marketing/apply'
    | '/_marketing/contact'
    | '/_marketing/features'
    | '/_marketing/pricing'
    | '/_marketing/use-cases'
    | '/auth/check-email'
    | '/auth/create-password'
    | '/auth/redirect'
    | '/auth/signin'
    | '/auth/signin-or-signup'
    | '/console/create-organization'
    | '/console/processing'
    | '/console/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketingRoute: typeof MarketingRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthCreatePasswordRoute: typeof AuthCreatePasswordRoute
  AuthRedirectRoute: typeof AuthRedirectRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSigninOrSignupRoute: typeof AuthSigninOrSignupRoute
  ConsoleCreateOrganizationRoute: typeof ConsoleCreateOrganizationRoute
  ConsoleProcessingRoute: typeof ConsoleProcessingRoute
  ConsoleWelcomeRoute: typeof ConsoleWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/welcome': {
      id: '/console/welcome'
      path: '/console/welcome'
      fullPath: '/console/welcome'
      preLoaderRoute: typeof ConsoleWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/processing': {
      id: '/console/processing'
      path: '/console/processing'
      fullPath: '/console/processing'
      preLoaderRoute: typeof ConsoleProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/create-organization': {
      id: '/console/create-organization'
      path: '/console/create-organization'
      fullPath: '/console/create-organization'
      preLoaderRoute: typeof ConsoleCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin-or-signup': {
      id: '/auth/signin-or-signup'
      path: '/auth/signin-or-signup'
      fullPath: '/auth/signin-or-signup'
      preLoaderRoute: typeof AuthSigninOrSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/redirect': {
      id: '/auth/redirect'
      path: '/auth/redirect'
      fullPath: '/auth/redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-password': {
      id: '/auth/create-password'
      path: '/auth/create-password'
      fullPath: '/auth/create-password'
      preLoaderRoute: typeof AuthCreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/auth/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/use-cases': {
      id: '/_marketing/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof MarketingUseCasesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/apply': {
      id: '/_marketing/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof MarketingApplyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingApplyRoute: typeof MarketingApplyRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingUseCasesRoute: typeof MarketingUseCasesRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingApplyRoute: MarketingApplyRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingUseCasesRoute: MarketingUseCasesRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketingRoute: MarketingRouteWithChildren,
  DashboardRoute: DashboardRoute,
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthCreatePasswordRoute: AuthCreatePasswordRoute,
  AuthRedirectRoute: AuthRedirectRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSigninOrSignupRoute: AuthSigninOrSignupRoute,
  ConsoleCreateOrganizationRoute: ConsoleCreateOrganizationRoute,
  ConsoleProcessingRoute: ConsoleProcessingRoute,
  ConsoleWelcomeRoute: ConsoleWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
